# Generated by Django 2.2 on 2021-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('phoneNo', models.IntegerField()),
                ('course', models.CharField(max_length=60)),
            ],
        ),
    ]
